### ISSUE TITLE
don't use working directory for config/logs

### ISSUE THREAD

**Issue by ashkitten** [Zingabopp/BeatSync#21]
at the moment, BeatSyncConsole uses files inside the current working directory, which is problematic as i want to add the executable to my PATH so i can run it from anywhere. as is, depending on where i run it from, it won't pick up the existing config and will litter the current directory with `configs`, `logs`, and `Temp`

on linux it should probably use a folder according to the XDG standard (usually under `~/.config`) for the `configs` and `logs` directories, and assuming `Temp` is what it says, it can use `mktemp` to have the system create a temporary directory for it.

**Comment by Zingabopp** [comment]
See if this works to your satisfaction: https://github.com/Zingabopp/BeatSync/actions/runs/195766588
* Directories for configs, logs, and temp are now relative to the assembly file location instead of working directory.
* I included an option for the system temp folder. For the configs and logs, I'd prefer them to remain in the folder with the assembly (portable), but I may add an option specific to the Linux build.

**Comment by ashkitten** [comment]
having configs and logs next to the assembly won't work for me specifically since i'm actually building and installing the program myself with nix (https://github.com/ashkitten/nixos-config/blob/master/packages/BeatSyncConsole/default.nix). a cli option or environment variable to specify the config/log directories would work, since i can just add it to the wrapper... but it would certainly be nice to just use xdg dirs like QBeat does

**Comment by Zingabopp** [comment]
CLI options for config/log directories added.
* -c <PATH> for config directory.
* -L <PATH> for log directory.
https://github.com/Zingabopp/BeatSync/actions/runs/196027002

**Comment by ashkitten** [comment]
that works for me, thanks

**Comment by Zingabopp** [comment]
Official release: https://github.com/Zingabopp/BeatSync/releases/tag/0.9.0
