### ISSUE TITLE
Songs double check

### ISSUE THREAD

**Issue by StCost** [Zingabopp/BeatSync#40]
Please, add two additional checks:
1) Check is song still bookmarked, followed, curator recommended, etc. If not - delete it from folder.
2) If song should have been on it's machine but doesn't exist (e.g. was deleted manually) - download it again
Thanks

**Comment by Zingabopp** [comment]
I'm not a fan of having BeatSync delete songs, too many ways for that to go wrong. Not redownloading manually deleted songs is intended behavior (that's what the history file is for) so that BeatSync doesn't keep downloading songs you don't want. If you want to redownload songs, you can delete the `BeatSyncHistory.json` file. If you would like your feed playlists to only contain songs that are currently in the feed (removing songs you unbookmark), you can change the PlaylistStyle to `Replace` in `BeatSync.json`
